import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "./ui/home/footer";
import AuthProvider from "./sessionProvider";
import { headers } from "next/headers";
import { sessionInfo } from "./api/auth/[...nextauth]/options";
import Header from "./ui/home/header";
import Navigation from "./ui/home/navigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Os Donos da Rua | Início",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await sessionInfo();

  console.log(session);
  return (
    <AuthProvider>
      <html lang="en">
        <body className={inter.className}>
          {session ? <Navigation /> : <Header session={session} />}
          {children}
          {!session && <Footer />}
        </body>
      </html>
    </AuthProvider>
  );
}
